'use strict';
var w2v = require("./lib");
var modelFile = "./data/test.model.bin";
// var w2v = new Word2Vector( modelFile );
w2v.load( modelFile );
var a = w2v.getVector('唐三藏');
// var b = w2v.getVectors(['孫悟空'], "Object")['孫悟空'];
// var c = [];
// for(var i=0; i<a.length; i++) c.push(a[i] - b[i]);
var d = w2v.getNearest(a);
console.log(d);
